image: microsoft/dotnet:2.1-sdk

stages:
  - build
  - test
  - deploy

variables:
  PROJECT_DIR: "ElronAPI.Api"

test:
  stage: test
  script:
    - dotnet restore
    - dotnet test ElronAPI.Tests/ElronAPI.Tests.csproj

build:
  stage: build
  script:
    - cd $PROJECT_DIR
    - dotnet restore
    - dotnet build
    - dotnet publish -c Release -o obj/App/publish
  artifacts:
    expire_in: 1 month
    paths:
      - $PROJECT_DIR/obj/App/publish/*